export const INIT_CHARACTERS = 'INIT_CHARACTERS';
export const GET_NEXT_CHARACTERS = 'GET_NEXT_CHARACTERS';
export const START_LOADING_CHARACTERS = 'START_LOADING_CHARACTERS';
export const GET_NEXT_CHARACTERS_FROM_BUFFER = 'GET_NEXT_CHARACTERS_FROM_BUFFER';
export const GET_CHARACTER_DATA = 'GET_CHARACTER_DATA';
export const GET_FILMS = 'GET_FILMS';
